# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8006d1ac4be7b399f48e1f544181102b9602c2f1493957d041ad3b233bd10624117562ea335d7f2a4824ab2e43e5e252320d2cd7da5dbe75ff60d17c96be69cf

test:
  secret_key_base: f38d04a9b149f800825fafaae6749ce23e838355a0a57ab274b6343d4acdfc24337e44901c7abbc07330635b282c17210a396fdb82bc1b516643d0b919ed9a12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
